# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Runs all the tests"
  lane :test do
      gradle(task: "test")

      automated_test_emulator_run(
        AVD_setup_path: "fastlane/AVD/AVD_setup.json",
        gradle_task: "connectedAndroidTest",
        AVD_param_launch_timeout: "120"
      )

      gradle(task: "dokka")

      slack(message: "Frollo Android SDK Successfully Integrated!",
            default_payloads: [:git_branch, :lane, :test_result],
            success: true)
  end

end

def on_error(exception)
       slack(
           message: "Frollo Android SDK integration failed with exception : #{exception}",
           success: false,
       )
end
